### ISSUE TITLE
Compile error with gcc 9.3.1

### ISSUE THREAD

**Issue by est77** [undisbeliever/untech-editor#1]
src/models/project/project-data.cpp: In instantiation of ‘bool UnTech::Project::ProjectData::compileList(ConvertFunction, UnTech::Project::DataStore<DataT>&, UnTech::ResourceType, const InputListT&, const PreresquitesT& ...) [with DataT = UnTech::MetaTiles::MetaTileTilesetData; ConvertFunction = std::shared_ptr<const UnTech::MetaTiles::MetaTileTilesetData> (*)(const UnTech::MetaTiles::MetaTileTilesetInput&, const UnTech::Project::DataStore<UnTech::Resources::PaletteData>&, const UnTech::MetaTiles::InteractiveTilesData&, UnTech::ErrorList&); InputListT = UnTech::ExternalFileList<UnTech::MetaTiles::MetaTileTilesetInput>; PreresquitesT = {UnTech::Project::DataStore<UnTech::Resources::PaletteData>, std::shared_ptr<const UnTech::MetaTiles::InteractiveTilesData>}]’:
src/models/project/project-data.cpp:849:102:   required from here
src/models/project/project-data.cpp:740:61: error: call of overloaded ‘compileListItem<UnTech::MetaTiles::MetaTileTilesetData>(std::shared_ptr<const UnTech::MetaTiles::MetaTileTilesetData> (*&)(const UnTech::MetaTiles::MetaTileTilesetInput&, const UnTech::Project::DataStore<UnTech::Resources::PaletteData>&, const UnTech::MetaTiles::InteractiveTilesData&, UnTech::ErrorList&), const UnTech::ExternalFileList<UnTech::MetaTiles::MetaTileTilesetInput>&, unsigned int&, const UnTech::Project::DataStore<UnTech::Resources::PaletteData>&, const std::shared_ptr<const UnTech::MetaTiles::InteractiveTilesData>&)’ is ambiguous
  740 |                 auto [status, data] = compileListItem<DataT>(convertFunction, inputList, index, prerequisites...);
      |                                       ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/models/project/project-data.cpp:568:1: note: candidate: ‘std::pair<UnTech::Project::ResourceStatus, std::shared_ptr<const _Tp> > UnTech::Project::compileListItem(ConvertFunction, const InputListT&, unsigned int, const PreresquitesT& ...) [with DataT = UnTech::MetaTiles::MetaTileTilesetData; ConvertFunction = std::shared_ptr<const UnTech::MetaTiles::MetaTileTilesetData> (*)(const UnTech::MetaTiles::MetaTileTilesetInput&, const UnTech::Project::DataStore<UnTech::Resources::PaletteData>&, const UnTech::MetaTiles::InteractiveTilesData&, UnTech::ErrorList&); InputListT = UnTech::ExternalFileList<UnTech::MetaTiles::MetaTileTilesetInput>; PreresquitesT = {UnTech::Project::DataStore<UnTech::Resources::PaletteData>, std::shared_ptr<const UnTech::MetaTiles::InteractiveTilesData>}]’
  568 | compileListItem(ConvertFunction convertFunction,
      | ^~~~~~~~~~~~~~~
src/models/project/project-data.cpp:578:1: note: candidate: ‘std::pair<UnTech::Project::ResourceStatus, std::shared_ptr<const _Tp> > UnTech::Project::compileListItem(ConvertFunction, const UnTech::ExternalFileList<InputT>&, unsigned int, const PreresquitesT& ...) [with DataT = UnTech::MetaTiles::MetaTileTilesetData; ConvertFunction = std::shared_ptr<const UnTech::MetaTiles::MetaTileTilesetData> (*)(const UnTech::MetaTiles::MetaTileTilesetInput&, const UnTech::Project::DataStore<UnTech::Resources::PaletteData>&, const UnTech::MetaTiles::InteractiveTilesData&, UnTech::ErrorList&); InputT = UnTech::MetaTiles::MetaTileTilesetInput; PreresquitesT = {UnTech::Project::DataStore<UnTech::Resources::PaletteData>, std::shared_ptr<const UnTech::MetaTiles::InteractiveTilesData>}]’
  578 | compileListItem(ConvertFunction convertFunction,
      | ^~~~~~~~~~~~~~~
src/models/project/project-data.cpp: In instantiation of ‘bool UnTech::Project::ProjectData::compileList(ConvertFunction, UnTech::Project::DataStore<DataT>&, UnTech::ResourceType, const InputListT&, const PreresquitesT& ...) [with DataT = UnTech::Rooms::RoomData; ConvertFunction = std::shared_ptr<const UnTech::Rooms::RoomData> (*)(const UnTech::Rooms::RoomInput&, const UnTech::Resources::CompiledScenesData&, const UnTech::Entity::CompiledEntityRomData&, const UnTech::Rooms::RoomSettings&, UnTech::ErrorList&); InputListT = UnTech::ExternalFileList<UnTech::Rooms::RoomInput>; PreresquitesT = {std::shared_ptr<const UnTech::Resources::CompiledScenesData>, std::shared_ptr<const UnTech::Entity::CompiledEntityRomData>, UnTech::Rooms::RoomSettings}]’:
src/models/project/project-data.cpp:866:146:   required from here
src/models/project/project-data.cpp:740:61: error: call of overloaded ‘compileListItem<UnTech::Rooms::RoomData>(std::shared_ptr<const UnTech::Rooms::RoomData> (*&)(const UnTech::Rooms::RoomInput&, const UnTech::Resources::CompiledScenesData&, const UnTech::Entity::CompiledEntityRomData&, const UnTech::Rooms::RoomSettings&, UnTech::ErrorList&), const UnTech::ExternalFileList<UnTech::Rooms::RoomInput>&, unsigned int&, const std::shared_ptr<const UnTech::Resources::CompiledScenesData>&, const std::shared_ptr<const UnTech::Entity::CompiledEntityRomData>&, const UnTech::Rooms::RoomSettings&)’ is ambiguous
  740 |                 auto [status, data] = compileListItem<DataT>(convertFunction, inputList, index, prerequisites...);
      |                                       ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/models/project/project-data.cpp:568:1: note: candidate: ‘std::pair<UnTech::Project::ResourceStatus, std::shared_ptr<const _Tp> > UnTech::Project::compileListItem(ConvertFunction, const InputListT&, unsigned int, const PreresquitesT& ...) [with DataT = UnTech::Rooms::RoomData; ConvertFunction = std::shared_ptr<const UnTech::Rooms::RoomData> (*)(const UnTech::Rooms::RoomInput&, const UnTech::Resources::CompiledScenesData&, const UnTech::Entity::CompiledEntityRomData&, const UnTech::Rooms::RoomSettings&, UnTech::ErrorList&); InputListT = UnTech::ExternalFileList<UnTech::Rooms::RoomInput>; PreresquitesT = {std::shared_ptr<const UnTech::Resources::CompiledScenesData>, std::shared_ptr<const UnTech::Entity::CompiledEntityRomData>, UnTech::Rooms::RoomSettings}]’
  568 | compileListItem(ConvertFunction convertFunction,
      | ^~~~~~~~~~~~~~~
src/models/project/project-data.cpp:578:1: note: candidate: ‘std::pair<UnTech::Project::ResourceStatus, std::shared_ptr<const _Tp> > UnTech::Project::compileListItem(ConvertFunction, const UnTech::ExternalFileList<InputT>&, unsigned int, const PreresquitesT& ...) [with DataT = UnTech::Rooms::RoomData; ConvertFunction = std::shared_ptr<const UnTech::Rooms::RoomData> (*)(const UnTech::Rooms::RoomInput&, const UnTech::Resources::CompiledScenesData&, const UnTech::Entity::CompiledEntityRomData&, const UnTech::Rooms::RoomSettings&, UnTech::ErrorList&); InputT = UnTech::Rooms::RoomInput; PreresquitesT = {std::shared_ptr<const UnTech::Resources::CompiledScenesData>, std::shared_ptr<const UnTech::Entity::CompiledEntityRomData>, UnTech::Rooms::RoomSettings}]’
  578 | compileListItem(ConvertFunction convertFunction,
      | ^~~~~~~~~~~~~~~

**Comment by undisbeliever** [comment]
Commit e26c488 should fix the compile error (I do not have gcc 9.3.1 on my system).

Can you please confirm the fix compiles on gcc 9.3.1.

Thank-you for reporting this bug.

**Comment by est77** [comment]
Yes, compilation now finishes. I had to add -lpthread to link with pthreads.
I found another issue, I opened a new ticket for it.

Thanks!
