### ISSUE TITLE
Undefined references when building with gcc 9.3

### ISSUE THREAD

**Issue by est77** [undisbeliever/untech-editor#2]
I had some missing references to pthread that were easy to solve. After that, I now have:

in function `UnTech::Gui::MetaSpriteEditorGui::updateTilesetTexture()':
<artificial>:(.text+0x3f6e): undefined reference to `void UnTech::Snes::Tile<8ul>::draw<UnTech::Snes::Palette<4ul> >(UnTech::Image&, UnTech::Snes::Palette<4ul> const&, unsigned int, unsigned int, bool, bool) const'
/bin/ld: <artificial>:(.text+0x3fc2): undefined reference to `void UnTech::Snes::Tile<8ul>::draw<UnTech::Snes::Palette<4ul> >(UnTech::Image&, UnTech::Snes::Palette<4ul> const&, unsigned int, unsigned int, bool, bool) const'
/bin/ld: <artificial>:(.text+0x407d): undefined reference to `void UnTech::Snes::Tile<16ul>::draw<UnTech::Snes::Palette<4ul> >(UnTech::Image&, UnTech::Snes::Palette<4ul> const&, unsigned int, unsigned int, bool, bool) const'
/bin/ld: <artificial>:(.text+0x40cd): undefined reference to `void UnTech::Snes::Tile<16ul>::draw<UnTech::Snes::Palette<4ul> >(UnTech::Image&, UnTech::Snes::Palette<4ul> const&, unsigned int, unsigned int, bool, bool) const'
collect2: error: ld returned 1 exit status

**Comment by undisbeliever** [comment]
Commit 9d71055 should fix the missing pthread references and commit 5cd2fbb should fix the undefined references to `UnTech::Snes::Tile::draw`.

These fixes have been tested on a Ubuntu 20.04 LTS virtual machine (g++ 9.3.0).

Thanks again for reporting these issues.
